# Generated by Django 3.1 on 2020-10-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=64)),
                ('bought', models.BooleanField()),
                ('quantity', models.IntegerField(default=0)),
                ('share_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VirtualStockMarketApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='StocksOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VirtualStockMarketApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=64)),
                ('trait', models.CharField(choices=[('CB', 'cash_buy'), ('CS', 'cash_sell'), ('IS', 'intraday_sell'), ('IB', 'intraday_buy')], max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('status_pending', models.BooleanField(default=True)),
                ('limit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('share_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('GTC', models.BooleanField(null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VirtualStockMarketApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=64)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VirtualStockMarketApp.user')),
            ],
        ),
    ]
