# Generated by Django 3.1.1 on 2020-10-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0002_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=10000000.0, max_digits=50, null=True),
        ),
    ]
