# Generated by Django 3.1.1 on 2020-10-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0003_remove_user_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
