# Generated by Django 3.1.1 on 2020-10-11 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0003_auto_20201011_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='share_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 3, 51, 2, 945139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='limit_price',
            field=models.BooleanField(default=True),
        ),
    ]
