# Generated by Django 3.1.1 on 2020-10-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0004_auto_20201011_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
