# Generated by Django 3.1.1 on 2020-10-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0004_user_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
    ]
