# Generated by Django 3.1 on 2020-10-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0005_remove_user_is_authenticated'),
        ('VirtualStockMarketApp', '0002_favourites_stocksowned_transactionhistory'),
    ]

    operations = [
    ]
