# Generated by Django 3.1.1 on 2020-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0006_merge_20201006_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksowned',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
