# Generated by Django 3.1.1 on 2020-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0007_stocksowned_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksowned',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
