# Generated by Django 3.1 on 2020-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0007_auto_20201015_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intraday_balance',
            field=models.DecimalField(decimal_places=2, default=3000000.0, max_digits=50, null=True),
        ),
    ]
