# Generated by Django 3.1.1 on 2020-10-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0009_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksowned',
            name='quantity',
        ),
    ]
