# Generated by Django 3.1 on 2020-10-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0010_transactionhistory_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='trait',
            field=models.CharField(choices=[('CB', 'cash_buy'), ('CS', 'cash_sell'), ('IS', 'intraday_sell'), ('IB', 'intraday_buy'), ('SS', 'short_sell'), ('SB', 'short buy')], max_length=32),
        ),
    ]
