# Generated by Django 3.1.1 on 2020-10-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0010_remove_stocksowned_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=64)),
                ('trait', models.CharField(choices=[('CS', 'cash_sell'), ('CB', 'cash_buy'), ('IS', 'intraday_sell'), ('IB', 'intraday_buy')], max_length=32)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VirtualStockMarketApp.user')),
            ],
        ),
    ]
