# Generated by Django 3.1 on 2020-10-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0011_auto_20201027_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('balance', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=50, null=True)),
                ('intraday_balance', models.DecimalField(decimal_places=2, default=3000000.0, max_digits=50, null=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VirtualStockMarketApp.user')),
            ],
        ),
    ]
