# Generated by Django 3.1 on 2020-10-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualStockMarketApp', '0012_monthlyanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyanalysis',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='monthlyanalysis',
            name='intraday_balance',
        ),
        migrations.AddField(
            model_name='monthlyanalysis',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyanalysis',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
